### ISSUE TITLE
Obtaining an API key

### ISSUE THREAD

**Issue by volt4ire** [frdmn/alfred-imgur#1]
What should I set as the "Application name" and "Authorization callback URL" when registering for an imgur API key? 
<img width="792" alt="screen shot 2016-05-25 at 11 44 07 am" src="https://cloud.githubusercontent.com/assets/8772017/15546503/2b5cf19a-226e-11e6-99f2-0b9c8d62e3c5.png">

**Comment by frdmn** [comment]
Hi Robert,

I've used the following settings:
- <kbd>Authorization type</kbd>: `Anynmous usage without user authorization`
- <kbd>Authorization callback</kbd>: `https://imgur.com`  
  (you can use whatever you want since we don't need the callback, Imgur just wants you to set one)

Will mention that in the README.md later by today. 

Thanks for the hint :)
